name: CI
on: [push]
jobs:
  build:
    name: Build, lint, and test on Node
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'yarn'
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Install deps and build (with cache)
        run: yarn install

      - name: Lint
        run: yarn lint:ci

      - name: Test
        run: yarn test
